### PR TITLE
removing NCPFlash header file in flashratevector

### PR DESCRIPTION
**Pull request by GitPaean**
it does not look like used.

removing it will make the class more generic in some way.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
removing NCPFlash header file will make it one step further that other flash solver can use the same file.

**Comment by GitPaean** [comment]
jenkins build this please

**Review by akva2 — APPROVED** [review]
Yes, looks fine to me.

**Comment by GitPaean** [comment]
I am merging with the approval.

**Pull request merged**
