### PR TITLE
blackoilpolymermodules: include OpmLog.h

### PR DESCRIPTION
**Pull request by akva2**
Upstream changes will make this change necessary, however this can be merged separately as such.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by bska** [comment]
I don't understand the regression failures so I'll rerun the build check.  I **suspect** the failures were due to the reference solutions and/or opm-simulators being updated while the build check was running.

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
The earlier failure was a race condition and the build check is green now.  I'll merge into master.

**Pull request merged**
