### PR TITLE
Communicators2

### PR DESCRIPTION
**Pull request by ElyesAhmed**
adding the  communicator as input for the simulator calls

### CODE REVIEW

**Review by blattms — COMMENTED** [review]
Might be worth squashing the commits such that the branch only consits of one commit.
Apart from that this looks good.

**Comment by blattms** [comment]
Once this is one commit (yell, if you need help), I would merge this after a jenkins run.

**Comment by atgeirr** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
Thanks @ElyesAhmed for the PR and @blattms for reviewing, all is green and one commit so I'll merge.

**Pull request merged**
