### PR TITLE
Fix QuadMath handling

### PR DESCRIPTION
**Pull request by akva2**
And fix a test that is now activated since we build with dune-alugrid

Downstream of https://github.com/OPM/opm-common/pull/4132

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this opm-common=4132 please

**Comment by akva2** [comment]
jenkins build this opm-common=4132 please

**Comment by akva2** [comment]
jenkins build this opm-common=4132 please

**Comment by akva2** [comment]
jenkins build this opm-common=4132 please

**Comment by akva2** [comment]
jenkins build this opm-common=4132 please

**Comment by akva2** [comment]
jenkins build this opm-common=4132 please

**Review by bska — APPROVED** [review]
Okay, thanks.  I guess we'll strive to re-enable these tests Soon[tm].  I'll merge into master.

**Pull request merged**
