### PR TITLE
Fix Todd-Longstaff model for density. 

### PR DESCRIPTION
**Pull request by totto82**
Only modify density (i.e) the effective gravity contribution and not the volumes itself.

### CODE REVIEW

**Comment by totto82** [comment]
Based on testing against test case 2.1 in "A benchmark study on problems related to CO2 storage
in geologic formations"  https://link.springer.com/article/10.1007/s10596-009-9146-x

**Comment by totto82** [comment]
jenkins build this please

**Comment by bska** [comment]
I haven't looked at this in any kind of detail, but I'm guessing that the base branch is too old. The build failure references version 2022.10 and that suggests to me that you may need to rebase this onto current master.

**Comment by totto82** [comment]
Any review on this? I think the current implementation is wrong. With this fix we reproduce similar results as other simulators in the benchmark study.

**Comment by totto82** [comment]
Since nobody volunteered to review this I will self-merge tomorrow after updating the data. This only affects the solvent model and fixes a bug for the effective density calculations.

**Comment by totto82** [comment]
jenkins build this update_data please

**Pull request merged**
