### PR TITLE
Get rid of deck usage in BlackoilBrineModule

### PR DESCRIPTION
**Pull request by akva2**
As a consequence we do not have to serialize it any longer.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this opm-simulators=2408 please

**Comment by akva2** [comment]
jenkins run norne norne_parallel please

**Comment by blattms** [comment]
Sigh, let the regression hunting begin...

**Comment by akva2** [comment]
jenkins run norne norne_parallel opm-simulators=2408 please

**Comment by akva2** [comment]
Would be nice to get this merged now.

**Comment by blattms** [comment]
:+1: Merging,

**Pull request merged**
