### PR TITLE
add tpfa diffusion

### PR DESCRIPTION
**Pull request by GitPaean**
fixed tpfa for diffusion module

This replaces https://github.com/OPM/opm-models/pull/824 for convenience.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this opm-simulators=4825 please

**Comment by GitPaean** [comment]
jenkins build this opm-simulators=4825 please

**Comment by GitPaean** [comment]
jenkins build this opm-simulators=4825 please

**Comment by GitPaean** [comment]
jenkins build this opm-simulators=4825 please

**Comment by GitPaean** [comment]
jenkins build this opm-simulators=4825 please

**Review by totto82 — APPROVED** [review]
Thanks. Looks good to me.

**Review by akva2 — APPROVED** [review]
I have no comment.

**Comment by GitPaean** [comment]
Thanks for the approvals. I am getting it in now.

**Pull request merged**
