### PR TITLE
use rockfraction instead of 1 - porosity in energy equation

### PR DESCRIPTION
**Pull request by totto82**
Rock fraction is usually 1 - porosity, but if pvmult is used to modify porosity
we will apply the same multiplier to the rock fraction
i.e. pvmult*(1 - porosity) and thus interpret multpv as a volume
multiplier. This is to avoid negative rock volume for pvmult*porosity > 1

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this opm-simulators=4559 please

**Comment by totto82** [comment]
jenkins build this opm-simulators=4559 please

**Comment by bska** [comment]
jenkins build this please

**Comment by totto82** [comment]
The changes are very small and it should be safe to update the reference solution.

**Comment by akva2** [comment]
jenkins build this update_data please

**Comment by akva2** [comment]
jenkins build this opm-tests=943 please

**Comment by akva2** [comment]
please hit the green if this is ready.

**Comment by OPMUSER** [comment]
@totto82 Did this make it into 2023-04-RC1?

**Comment by totto82** [comment]
yes

**Pull request merged**
