### PR TITLE
Replace property system

### PR DESCRIPTION
**Pull request by berndflemisch**
Replace the property system such that it will be feasible to use it without preprocessor macros. This is achieved by employing more modern C++14 constructs. Redefine the macros in terms of the new system. Replacing the macro usages themselves will be done in a future PR.

While the system itself is concentrated in the file `opm/models/utils/propertysystem.hh` and the macro redefinitions in the file `opm/models/utils/propertysystemmacros.hh`, this PR affects all files that use the macro `NEW_PROP_TAG`. Before, this macro has been a forward declaration of a C++ struct. Now, it defines a struct template that is supposed to be specialized for specific type tags. In contrast to a declaration, the definition has to be stated exactly once.

The following tasks are to be completed before this is ready to be merged:
- [x] Replace the property splice mechanism
- [x] Remove all unnecessary forward declarations, replace necessary ones explicitly
- [x] Remove all leftovers from deleting the `NEW_PROP_TAG` usages

### CODE REVIEW

**Comment by atgeirr** [comment]
Thanks for this effort! I guess we need to figure out the splice system. I was never sure what it did specifically, anyone out there who knows?

**Comment by berndflemisch** [comment]
There's documentation in `opm/models/utils/propertysystem.hh`, line 190ff. It sounds useful. Inside opm-models, it is employed only at two places, but they are central: for defining a `SpatialDiscretizationSplice` for `MultiPhaseBaseModel` and for defining `LinearSolverSplice` and `LocalLinearizerSplice` for `FvBaseDiscretization`.

**Comment by berndflemisch** [comment]
For example, it allows you to set the spatial discretization by
```
SET_TAG_PROP(Tutorial1Problem, SpatialDiscretizationSplice, VcfvDiscretization);
```
The `SET_TAG_PROP` macro only works on splices. In Dumux, we would achieve this by inheriting the whole type tag:
```
NEW_TYPE_TAG(Tutorial1Problem, INHERITS_FROM(ImmiscibleTwoPhaseModel, VcfvDiscretization));
```
I'm unsure if we should try to maintain the splices functionality or if we should do it the way above. Currently, I tend to the former.

**Comment by andlaus** [comment]
interesting. Does your proposed new system support introspection? (a.k.a. `--print-properties=1`) I used this feature frequently to find out where what was defined and the feature is tremendously useful for newbies...

**Comment by berndflemisch** [comment]
Sorry, this feature had to go. And I don't see a way of keeping it as it was. The only easy thing in this direction would be to print the actual values for a predefined set of properties.

**Comment by berndflemisch** [comment]
I recovered the splice mechanism. At least tutorial1 compiles and seems to work.

**Comment by atgeirr** [comment]
> I recovered the splice mechanism. At least tutorial1 compiles and seems to work.

That is good news, perhaps we could try to make this transformation before the next release?

**Comment by berndflemisch** [comment]
We should try. Do you have deadlines?

**Comment by berndflemisch** [comment]
The test suite is up and running again. Next step is to clean up.

**Comment by berndflemisch** [comment]
This is close to completion. Which downstream modules should I check?

**Comment by berndflemisch** [comment]
Looks like there is only opm-simulators.

**Comment by blattms** [comment]
Cool.

Yep, opm-simulators should be the only one.

**Comment by berndflemisch** [comment]
I filed OPM/opm-simulators#2624 which should be merged at the same time as this one. How can this be achieved technically?

**Comment by berndflemisch** [comment]
Are the OPM modules supposed to pass `make headercheck`?

**Comment by GitPaean** [comment]
A jenkins test is triggered through OPM/opm-simulators#2624 along with this PR.

**Comment by akva2** [comment]
jenkins build this opm-simulators=2624 please

**Comment by akva2** [comment]
got further now, installation of linalgproperties.hh is missing.

**Comment by berndflemisch** [comment]
jenkins build this opm-simulators=2624 please

**Comment by berndflemisch** [comment]
Apparently, my `jenkins ...` words have no power. Can someone trigger this please?

**Comment by bska** [comment]
jenkins build this opm-simulators=2624 please

**Comment by berndflemisch** [comment]
Sorry, I forgot to add another new file to the install list. Can someone please trigger another test?

**Comment by akva2** [comment]
jenkins build this opm-simulators=2624 please

**Comment by berndflemisch** [comment]
I can't reproduce the failing build on Jenkins. Is it possible to set up the test container locally?

**Comment by bska** [comment]
jenkins build this opm-simulators=2624 please

**Comment by berndflemisch** [comment]
Still gives the same error
```In file included from /var/lib/jenkins/workspace/opm-models-PR-builder/mpi/install/include/opm/models/utils/propertysystem.hh:278,
                 from /var/lib/jenkins/workspace/opm-models-PR-builder/mpi/install/include/opm/models/utils/parametersystem.hh:35,
                 from /var/lib/jenkins/workspace/opm-models-PR-builder/deps/opm-simulators/opm/simulators/linalg/FlowLinearSolverParameters.hpp:30,
                 from /var/lib/jenkins/workspace/opm-models-PR-builder/deps/opm-simulators/opm/simulators/linalg/BlackoilAmg.hpp:24,
                 from /var/lib/jenkins/workspace/opm-models-PR-builder/deps/opm-simulators/tests/test_blackoil_amg.cpp:24:
/var/lib/jenkins/workspace/opm-models-PR-builder/mpi/install/include/opm/models/utils/propertysystemmacros.hh:41:2: warning: #warning "Property macros are deprecated and will be removed after release 2021.04. If you are not using property macros you can disable this warning by setting OPM_ENABLE_OLD_PROPERTY_MACROS to 0 (false) when configuring OPM. OPM_ENABLE_OLD_PROPERTY_MACROS defaults to 1 (true) until release 2020.10. After release 2020.10 it will default to 0 (false) so you will have to manually enable property macros in order to use them." [-Wcpp]
 #warning "Property macros are deprecated and will be removed after release 2021.04. \
  ^~~~~~~
In file included from /var/lib/jenkins/workspace/opm-models-PR-builder/mpi/install/include/opm/models/utils/propertysystem.hh:278,
                 from /var/lib/jenkins/workspace/opm-models-PR-builder/mpi/install/include/opm/models/utils/parametersystem.hh:35,
                 from /var/lib/jenkins/workspace/opm-models-PR-builder/deps/opm-simulators/opm/simulators/linalg/FlowLinearSolverParameters.hpp:30,
                 from /var/lib/jenkins/workspace/opm-models-PR-builder/deps/opm-simulators/opm/simulators/linalg/BlackoilAmg.hpp:24,
                 from /var/lib/jenkins/workspace/opm-models-PR-builder/deps/opm-simulators/tests/test_blackoil_amg.cpp:24:
/var/lib/jenkins/workspace/opm-models-PR-builder/deps/opm-simulators/opm/simulators/linalg/FlowLinearSolverParameters.hpp:85:37: error: 'LinearSolverBackend' is not a class template
 SET_TYPE_PROP(FlowIstlSolverParams, LinearSolverBackend, Opm::ISTLSolverEbos<TypeTag>);
                                     ^~~~~~~~~~~~~~~~~~~
/var/lib/jenkins/workspace/opm-models-PR-builder/mpi/install/include/opm/models/utils/propertysystemmacros.hh:234:12: note: in definition of macro 'SET_TYPE_PROP'
     struct PropTagName<TypeTag, TTAG(EffTypeTagName)>             \
            ^~~~~~~~~~~
make[2]: *** [CMakeFiles/test_blackoil_amg.dir/build.make:63: CMakeFiles/test_blackoil_amg.dir/tests/test_blackoil_amg.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2120: CMakeFiles/test_blackoil_amg.dir/all] Error 2
```
I don't get this error on my machine. With "set up the test container locally", I meant if I can set up the container here on my local machine.

**Comment by berndflemisch** [comment]
I did the obvious and included the corresponding header in OPM/opm-simulators#2624. So maybe you can give it one more go?

**Comment by akva2** [comment]
hmm, i can reproduce locally, using both gcc and clang. with the added include it now builds fine.

**Comment by akva2** [comment]
jenkins build this opm-simulators=2624 please

**Comment by GitPaean** [comment]
Maybe for opm-models you need `-DBUILD_TESTING=ON` to reproduce this?

**Comment by akva2** [comment]
As the failure was is in a test in opm-simulators, that would be very surprising to say the least.

**Comment by berndflemisch** [comment]
I went with `make test-suite` in opm-simulators which includes the offending target `test_blackoil_amg`. Also an explicit `make test_blackoil_amg` worked fine.

**Comment by GitPaean** [comment]
With `-DBUILD_TESTING=ON`, opm-models shows the following building error locally
```
  506 In file included from /home/kaib/OPM-PR-test/debug/opm-models/opm/models/utils/start.hh:36,
  507                  from /home/kaib/OPM-PR-test/debug/opm-models/tutorial/tutorial1.cc:30:
  508 /home/kaib/OPM-PR-test/debug/opm-models/opm/models/utils/parametersystem.hh: In static member function ‘static ParamType Opm::Parameters::Param<TypeTag>::retrieve_(const char*, const ParamType&, bool)’:
  509 /home/kaib/OPM-PR-test/debug/opm-models/opm/models/utils/parametersystem.hh:1058:46: error: ‘propTagName’ was not declared in this scope
  510  1058 |         check_(Dune::className<ParamType>(), propTagName, paramName);
  511       |                                              ^~~~~~~~~~~
  512 In file included from /home/kaib/OPM-PR-test/debug/opm-models/opm/models/blackoil/b
```

It is with DUNE2.6

**Comment by berndflemisch** [comment]
Can you maybe post the exact output of `make VERBOSE=1 tutorial1`

**Comment by GitPaean** [comment]
You can take a look, but do not spend time on it if it is not that relevant, because Jenkins did not give this failure.

[log.zip](https://github.com/OPM/opm-models/files/4649564/log.zip)

**Comment by GitPaean** [comment]
Jenkins passes.

**Comment by berndflemisch** [comment]
If you encounter the problem, there's a high chance someone else will, too. I still don't see the flags. Can you go to the build directory and
```
make VERBOSE=1 tutorial1
```
Or maybe add
```
MAKE_FLAGS="VERBOSE=1"
```
to your opts file.

**Comment by GitPaean** [comment]
In the attached log file above, there is the flags, 
```
  24 /usr/bin/mpicxx  -DBOOST_ALL_NO_LIB -DBOOST_DATE_TIME_DYN_LINK -DBOOST_SYSTEM_DYN_LINK -DBOOST_TEST_DYN_LINK -DBOOST_UNIT_TEST_FRAMEWORK_DYN_LINK -DDUNE_COMMON_FIELDVECTOR_SIZE_IS_METHOD=1 -DENABLE_TBB=1      -DHAVE_CONFIG_H=1 -DSILENCE_EXTERNAL_WARNINGS -D_TBB_CPP0X -I/home/kaib/OPM-PR-test/debug/opm-models-build -I/home/kaib/OPM-PR-test/debug/opm-models -I/home/kaib/local/dune2.6.0/release2.6.0_O3_mpi/incl     ude -I/usr/include/suitesparse -I/home/kaib/OPM-PR-test/debug/opm-common -I/home/kaib/OPM-PR-test/debug/opm-common/external/cjson -I/home/kaib/OPM-PR-test/debug/opm-common-build/include -I/home/kaib/OPM-     PR-test/debug/opm-material -I/home/kaib/OPM-PR-test/debug/opm-grid -I/usr/include/trilinos  -pipe -pedantic -Wall -Wextra -Wformat-nonliteral -Wcast-align -Wpointer-arith -Wmissing-declarations -Wcast-qu     al -Wshadow -Wwrite-strings -Wchar-subscripts -Wredundant-decls -fopenmp -pthread -O2 -g -DDEBUG   -fopenmp -std=c++17 -o CMakeFiles/tutorial1.dir/tutorial/tutorial1.cc.o -c /home/kaib/OPM-PR-test/debug/     opm-models/tutorial/tutorial1.cc
```

**Comment by berndflemisch** [comment]
Yes, sorry, I didn't see them. I'll check

**Comment by berndflemisch** [comment]
I can reproduce the error with your flags.

**Comment by berndflemisch** [comment]
It's `DEBUG` or missing `NDEBUG`. I guess that this triggers the property inspection mechanism which I have not fully taken care of.

**Comment by berndflemisch** [comment]
Should work now. @GitPaean can you maybe check with you debug settings? And to be on the safe side, we should trigger another Jenkins build, please.

**Comment by GitPaean** [comment]
jenkins build this opm-simulators=2624 please

**Comment by berndflemisch** [comment]
This looks fairly complete to me now. Let me briefly summarize this PR. In my view, it is the first of three steps/PRs:

1. Replace the property system by native C++. Redefine the macros as wrappers for this code and keep the macro calls.
2. Replace the macro calls by C++.
3. Separate properties and parameters.

The nice thing is that the first step gets away without changing any top-level code in opm-models and opm-simulators. And you should already see improved error messages. The second step should be a piece of cake, the third again more involved. What you gain is largely macro-free code and comprehensible error messages.

Nevertheless, this PR might break code downstream. The macro `NEW_PROP_TAG` was a declaration before and is now a definition. So if anywhere `NEW_PROP_TAG` is used as a forward declaration, this results in a `redefinition` error. In the two currently affected modules, one could very often simply delete the forward declaration. Sometimes, one had to include an additional header containing the definition. In rare cases of circular inclusions, one had to use an explicit forward declaration, namely,
```cpp
template <class TypeTag, class MyTypeTag>
struct PropertyTag;
```
instead of
```cpp
NEW_PROP_TAG(PropertyTag);
```

Another current potential drawback is that the run-time property inspection with the `printProperties` function got lost. I don't see any convenient way of reintroducing it in the exact old form, where the actually used property tree is printed. What I can imagine is to have a `printProperties` function that prints the values of manually defined properties, so there would be a list with the properties to be printed that would have to be kept up-to-date. If this is wanted, I would propose to add this functionality after Step 3 has been taken care of.

**Comment by atgeirr** [comment]
Thanks a lot for your effort, I really appreciate it! I do have one question:

> Another current potential drawback is that the run-time property inspection with the `printProperties` function got lost. I don't see any convenient way of reintroducing it in the exact old form, where the actually used property tree is printed.

I am not quite sure what feature you are referring to here. Will this affect the ability to write "--help" and get the available options, or the printout (currently to the .DBG file) of all parameters used in the run? I know I am confusing properties and parameters here, the relation is not 100% clear to me.

**Comment by GitPaean** [comment]
It looks like fixing my local building problem. Thanks @berndflemisch

**Comment by berndflemisch** [comment]
According to `start.hh`, property values are printed if
```cpp
        int printProps = EWOMS_GET_PARAM(TypeTag, int, PrintProperties);
        if (printProps && myRank == 0) {
            if (printProps == 1 || !isatty(fileno(stdout)))
```
The property `PrintProperties` is set to `2` by default. The property and corresponding parameter appear to be unchanged for all tests. I don't fully understand the `isatty` thing but would guess that the list is always printed if its output happens to a file. It should be a list starting with
```
###########
# Properties
###########
```
Maybe you can check?

**Comment by atgeirr** [comment]
> Maybe you can check?

The feature works if I set `--print-properties=1`. I think it is not much used, and we want to move on and get this merged. I see that it can be a nice help for the programmer new to the tags system, but on the other hand the current PR simplifies learning and understanding it, a net improvement I think. Also, it makes OPM more similar to Dumux, which in itself is a benefit.

I propose to merge this Thursday, unless significant concerns are raised. I expect lots of us will have to rebase working branches after this is merged, so if you have a branch that would be impacted in a major way, please say so, and we could try to get it in first. If no-one shouts we go ahead, but I promise not to merge this before Thursday so you have a chance to ask for a little extra time.

**Comment by blattms** [comment]
> 
> I propose to merge this Thursday, unless significant concerns are raised.

:+1: Thanks a lot for the hard work Bernd.

**Comment by GitPaean** [comment]
jenkins build this opm-simulators=2624 please

**Comment by bska** [comment]
I'd like to remove this branch from OPM's main repo.

**Comment by atgeirr** [comment]
> I'd like to remove this branch from OPM's main repo.

I agree, did not really notice it was not from a separate fork.

**Pull request merged**
