### PR TITLE
implement dirichlet boundary conditions

### PR DESCRIPTION
**Pull request by totto82**
Depends on OPM/opm-common#3185

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this please

**Comment by blattms** [comment]
jenkins build this with opm-simulators=4182

**Comment by blattms** [comment]
jenkins build this opm-simulators=4182 please

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this opm-simulators=4182 please

**Pull request merged**
