### PR TITLE
BlackoilPrimaryVariables: add serialization support

### PR DESCRIPTION
**Pull request by akva2**
For restart.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this opm-common=3383 opm-simulators=4421 please

**Review by bska — COMMENTED** [review]
I don't see an `operator==() const` here.  Am I missing something?

**Comment by akva2** [comment]
jenkins build this opm-simulators=4421 please

**Review by bska — APPROVED** [review]
Thanks for the updates.  I'll merge into master.

**Pull request merged**
