### PR TITLE
add mpi serialization for BlackoilBrineModule

### PR DESCRIPTION
**Pull request by akva2**
Downstream of https://github.com/OPM/opm-material/pull/392

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this opm-simulators=2318 please

**Comment by akva2** [comment]
jenkins build this opm-simulators=2318 please

**Comment by totto82** [comment]
The test from opm-material was green.

**Comment by akva2** [comment]
jenkins build this opm-simulators=2318 please

**Pull request merged**
