### PR TITLE
removing compositional related from blackoilmodel.hh

### PR DESCRIPTION
**Pull request by GitPaean**
it is working in progress.

It aims at removing compostional related routines from blackoil related modules. There is a VtkBlackoil already.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please opm-simulators=4936 please

**Comment by totto82** [comment]
You can compute many of the output you typically have in a compositional simulation from the blackoil model. Some of this conversion is implemented in the BlackoilFluidSystem, some just outputs trivial numbers. It may be useful to look at molar fractions etc even in a blackoil simulations if you want to compare it with compositional simulations. Why do you want to remove it?

**Comment by GitPaean** [comment]
With the current form, when developing https://github.com/OPM/opm-models/pull/838, when we added more output to the VtKCompostional, since VtkCompostional is included in the BlackoilModel, then we have to update the BlackoilFluidState when we add more output to the VtkCompostional.  It might be a bad idea to keep filling the BlackoilFluidState with compostional related stuff, which causes confusion and maintenance burden. 

Then I think it might be a good idea to make sure the VtkCompostional and VtkBlackoil be more separated.  If not many compositional properties from Blackoil are needed to compare against the compositional results, maybe we can just put these few functions also in VtkBlackoil for now, and not include VtkCompostional in the BlackoilModel.  Even for outputting purpose, those are  still  serving and based on blackoil simulations. It is okay to have them in the VtkBlackoil. It is also introduce some maintenance burden, but hopefully more manageable. At least, not when working on compositional simulation and have to take care of the blackoil related.  

How do you think?

**Comment by GitPaean** [comment]
Thanks.  In the future, with some refactoring, we can do refactoring to reduce possible duplication.

**Comment by GitPaean** [comment]
@totto82 , are you okay with simply removing the including of the vtkcompostional from the blackoilmodel, or you prefer we can add the missing function to be vtkblackoil before removing?

I believe in the future, we can have another vtkmodule to handle the common one between compostional and blackoil models.

**Comment by GitPaean** [comment]
If we do not think `vtkcompositionmodule.hh` is for compsitional modeling. We think it is more composition information.  Maybe we should keep vtkcmositionmodule while have a vtkcompostionalmodule.hh (or different name) to handle the compositional simulation related.

**Comment by totto82** [comment]
> are you okay with simply removing the including of the vtkcompostional from the blackoilmodel

Yes. 

> we should keep vtkcmositionmodule while have a vtkcompostionalmodule.hh (or different name) to handle the compositional simulation related.

I am find with this solution as well. 

I suggest you do what you think is easiest in terms of getting something to work for the compositional runs. As I said the usage of compositional output from the blackoil model is probably not used by anybody. And if somebody needs it in the future it should be trivial to add i back.

**Comment by GitPaean** [comment]
Thanks for the discussion. It is in the files that I am not familiar with and some discussion is very helpful. 

At the end, I decided to introduce a new module vtkptflashmodule to avoid touching vtkcompostionmodule. 

In the future, there might be more refactoring. 

I will close this PR now.

**Pull request closed without merging**
