### PR TITLE
NewtonMethod: split parameters and properties

### PR DESCRIPTION
**Pull request by akva2**
Continuing #904

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this opm-simulators=5460 please

**Comment by akva2** [comment]
jenkins build this opm-simulators=5460 please

**Comment by akva2** [comment]
jenkins build this opm-simulators=5460 please

**Comment by akva2** [comment]
jenkins build this opm-simulators=5460 please

**Comment by akva2** [comment]
jenkins build this opm-simulators=5460 please

**Review by bska — APPROVED** [review]
Excellent.  I'll merge this and its downstream PR into the master branch.

**Pull request merged**
