### PR TITLE
Get rid of deck usage in BlackoilFoamModule

### PR DESCRIPTION
**Pull request by akva2**
As a consequence we do not need to serialize it any longer.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this opm-tests=251 opm-simulators=2407 please

**Comment by akva2** [comment]
jenkins build this opm-common=1533 opm-simulators=2407 please

**Comment by akva2** [comment]
Would be nice to get this merged now.

**Comment by blattms** [comment]
Looks good. Merging with downstream

**Pull request merged**
