### PR TITLE
Random Fixes

### PR DESCRIPTION
**Pull request by andlaus**
This PR contains a few random fixes for issues which I've stumbled upon during my recent OpenMP replacement spree. For the eWoms tests, avoiding to retrieve runtime parameters more often than necessary in the VTK output code leads to some sizeable speedup. (`flow` should be unaffected by this PR.)

### CODE REVIEW

**Comment by andlaus** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
> it would be nice if someone could test this on a somewhat exotic system. (I'm looking at your MacOS @atgeirr ;))

I'll test run it tomorrow at the latest.

**Comment by andlaus** [comment]
jenkins build this please

**Comment by andlaus** [comment]
> Why did you think clang or macOS could cause trouble BTW?

I didn't. MacOS has proven to be worthy of special attention in the past, though.

**Pull request merged**
