### PR TITLE
Set eq weights externally in the blackoil model

### PR DESCRIPTION
**Pull request by totto82**
Use the same weights here as in the getConvergence methods in the Flow part of the code. 
These weights are currently only used by the drift compensation code. 

We could consider using these weights instead of computing them over an over again in the getConvergence method. Initial testing indicates that this does not give any significant differences. That could give a decent speed-up since we then no-longer need to integrate over the elements jf recent work on speeding up the assembly.

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this opm-simulators=3968 please

**Comment by totto82** [comment]
jenkins build this opm-simulators=3968 please

**Comment by totto82** [comment]
jenkins build this opm-simulators=3968 please

**Comment by totto82** [comment]
Test failures are expected since the PR changes how the drift compensation is computed. Most of the failures are minor. 
The most significant failures are tested manually. The failures include restarts cases. Drift compensation is not accounted for in the restart files which could lead to some deviations between the original case and the restart case. I spend some time analyzing the SPE9 restart failure. Interestingly the results stay the same until the 21 report step when the restarted case use one less newton iteration resulting in deviations in the results. Using a stricter tolerance assures the results stay the same. The PR has also been tested by @tskille on field models with good results.  

```
         59 - compareECLFiles_flow+SPE5CASE1 (Failed) ok
         75 - compareECLFiles_flow+UDQ_ACTIONX (Failed) ok
        102 - compareECLFiles_flow+9_2B_DEPL_GCONPROD_2L_MSW (Failed) ok
        110 - compareECLFiles_flow+9_3D_GINJ_GAS_MAX_EXPORT_MSW (Failed) ok
        114 - compareECLFiles_flow+9_4A_WINJ_MAXWRATES_MAXBHP_GCONPROD_1L_MSW (Failed) ok
        122 - compareECLFiles_flow+MOD4_UDQ_ACTIONX (Failed) ok
        131 - compareECLFiles_flow+NORNE_ATW2013_B1H_RE-PERF (Failed) ok
        143 - compareECLFiles_flow+BASE_WT_TRACER (Failed) ok
        151 - compareECLFiles_flow+MAX_WATERCUT_1 (Failed) good match with --enable-tuning=true
        154 - compareECLFiles_flow+MAX_WATERCUT_4 (Failed) good match with --enable-tuning=true
        159 - compareRestartedSim_flow+SPE9_CP_SHORT (Failed) pass with strict mb tolerance
        162 - compareRestartedSim_flow+3D_1AQU_3CELLS (Failed) changed tolerance to make it pass
```

**Comment by totto82** [comment]
jenkins build this opm-simulators=3968 please

**Comment by totto82** [comment]
jenkins build this opm-simulators=3968 please

**Comment by totto82** [comment]
jenkins build this opm-simulators=3968 please

**Review by blattms — APPROVED** [review]

**Comment by totto82** [comment]
jenkins build this opm-simulators=3968 please

**Comment by totto82** [comment]
jenkins build this opm-simulators=3968 please

**Comment by totto82** [comment]
jenkins build this opm-simulators=3968 update_data please

**Comment by blattms** [comment]
jenkins build this opm-simulators=3968 opm-tests=795 please

**Pull request merged**
