### PR TITLE
fix almost filled with water to 1.0-1e-6

### PR DESCRIPTION
**Pull request by totto82**
This is the third part of https://github.com/OPM/opm-models/pull/803

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by hnil** [comment]
Probably put it in the tag system to be changed. Maybe we should add a type DefaultTolerances where one could get forexample (if it do not exist):
using NumTol = GetPropertyType<TypeTag, DefaultTolerances>;
static constexpr myeps = NumTol::eps;

Reasons: 
- be able to change them
- avoid putting it as hidden defaut input
- collect numbers used for numerical hacks ++ one place
- avoid all the boiler plate assosiated with input parameter i.e. tag definitions, init, register.

**Comment by totto82** [comment]
benchmark please

**Comment by totto82** [comment]
> Probably put it in the tag system to be changed.

Good point. Especially since it seem to affect lot of cases.

**Comment by totto82** [comment]
benchmark please

**Pull request closed without merging**
