### PR TITLE
move the boundary check downstream

### PR DESCRIPTION
**Pull request by totto82**
Should fix test failure in opm-models. 
Solution suggested by @blattms

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this opm-simulators=3107 please

**Comment by akva2** [comment]
the error is only visible when building without mpi so better include serial in that trigger.

**Comment by akva2** [comment]
jenkins build this opm-simulators=3107 serial please

**Comment by akva2** [comment]
fixes the issue, suggested by one dev and submitted by another. i'll merge this now to restore full CI.

**Pull request merged**
