### PR TITLE
Put properties of Newton method into separate header for reuse.

### PR DESCRIPTION
**Pull request by blattms**
Now they can be reused in opm-simulators without any hassle.
There will be a downstream change.

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this opm-simulators=4185 please

**Comment by blattms** [comment]
Yeah, what do know.
Properties with the same name have to registered with the exact same arguments no matter whether the template parameter is different. That is a bit of a pity as 
- we need to used the same number of iterations both in models an in simulators (not a big deal, we can simply used 20 for both)
- The bigger problem is the usage string (models: "The maximum number of Newton iterations per time step" and simulators: "The maximum number of Newton iterations per time step used by flow")

"by flow" is of coarse a bit redundant information, but if we skip that we would need to skip it everywhere for consistency. Which in particular means changing all these in simulators(NonlinearSolverEbos) and probably more;
```
                EWOMS_REGISTER_PARAM(TypeTag, Scalar, NewtonMaxRelax, "The maximum relaxation factor of a Newton iteration used by flow");
                EWOMS_REGISTER_PARAM(TypeTag, int, NewtonMaxIterations, "The maximum number of Newton iterations per time step used by flow");
                EWOMS_REGISTER_PARAM(TypeTag, int, NewtonMinIterations, "The minimum number of Newton iterations per time step used by flow");
                EWOMS_REGISTER_PARAM(TypeTag, std::string, NewtonRelaxationType, "The type of relaxation used by flow's Newton method");
```

Comments?

**Comment by blattms** [comment]
Last commit in opm-simulators accomplishes the  latter (removing references of flow for Newton).

**Comment by blattms** [comment]
jenkins build this opm-simulators=4185 please

**Comment by atgeirr** [comment]
> Last commit in opm-simulators accomplishes the latter (removing references of flow for Newton).

I am in favour of doing that.

**Comment by blattms** [comment]
Then we should probably merge this and the other one.

**Comment by blattms** [comment]
jenkins build this opm-simulators=4185 please

**Review by bska — APPROVED** [review]
Thanks a lot.  This looks good to me now and I'll merge this and its downstream companion int master now.

**Pull request merged**
