### PR TITLE
Faster assembly minimal

### PR DESCRIPTION
**Pull request by atgeirr**
This is a partial successor to #698. There are developments in that branch that are not included here, in order to make this PR smaller and more focused. It now focuses only on assembly (linearization) performance, anything related to faster property evaluation is not included, and will be left for future PRs.

In order to use the two new facilities (the TpfaLinearizer, and the BlackoilLocalResidualTpfa), the classes must be requested in the simulator type tag. This is done in the corresponding code in opm-simulators, but only for a single, separate flow variant for now (flow_blackoil_tpfa.cpp). The refactoring done in blackoilintensivequantities here also require changes to eclproblem.hh in opm-simulators.

This PR can be merged in my opinion. It must be merged together with the opm-simulators PR, which is almost ready at the time of writing this.

### CODE REVIEW

**Comment by atgeirr** [comment]
jenkins build this opm-simulators=3988 please

**Comment by atgeirr** [comment]
jenkins build this opm-simulators=3988 please

**Comment by atgeirr** [comment]
jenkins build this opm-simulators=3988 please

**Comment by bska** [comment]
I've not looked at this at all but I notice that there are a number of [new warnings](https://ci.opm-project.org/job/opm-models-PR-builder/183/gcc/new/) following the latest CI build.  Will you address those before the review is finalised?

**Comment by atgeirr** [comment]
Not sure why I did not see the warnings locally, but I have now addressed them. Turned out I could remove a whole lot of `timeIdx` parameters.

If there are no new warnings I hope this can be merged when green again.

**Comment by bska** [comment]
jenkins build this opm-simulators=3988 please

**Comment by atgeirr** [comment]
All green, no new warnings, acceptance indicated by @totto82 and others. Merging now.

**Pull request merged**
