### PR TITLE
fixed: inconsistent parameter setups

### PR DESCRIPTION
**Pull request by akva2**
registered as int and obtained as unsigned, or registered as Scalar and obtained as int

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Review by bska — COMMENTED** [review]
This PR chooses to register the parameters as the retrieved type instead of retrieving the parameters as the registered type.  Is there a particular reason for this choice or are both choices equally valid from a technical point of view?

**Comment by akva2** [comment]
Either would be fine apart from the Scalar one that obviously is a cut and paste issue.

**Review by bska — APPROVED** [review]
> My reason for [registering the retrieved type is that] that will be the effect of #888 as in this is the way to not change the user code.

Okay, very good.  The problem of a user passing a negative value as the argument to a parameter of type `unsigned int` is (probably) the same before and after this change so I'll merge into master.

**Comment by akva2** [comment]
for the record; yes, when the cast happens differ but result it exactly the same.

**Pull request merged**
