### PR TITLE
remove EWOMS_END_PARAM_REGISTRATION macro

### PR DESCRIPTION
**Pull request by akva2**
it adds no simplicity and only obfuscates

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this opm-simulators=5269 please

**Comment by blattms** [comment]
Using the macro seems to indicate that we can now safely assume that all parameters are registered. E.g. to be sure that --help will print everything.

By removing it we cannot assume that at any stage. Might not really be a problem, though.

**Comment by akva2** [comment]
That would be true if i did not replace the macro usage with the direct call instead....

**Review by bska — APPROVED** [review]
Thanks.  This looks good to me and I'll merge into master.

**Pull request merged**
