### PR TITLE
Simulator: add serialization support

### PR DESCRIPTION
**Pull request by akva2**
Sits on top of #780

### CODE REVIEW

**Review by bska — COMMENTED** [review]
This is probably okay, but in previous PRs of this kind there has usually been `operator==()` and a `serializeOp()` member functions.  Do we need those here?

**Comment by akva2** [comment]
not really. this is, basically,  the top level of the serialization. a test here is the same as running a full simulator, and that is more the job for a regression test (which are eventually added further down the chain).

**Review by bska — COMMENTED** [review]
>> Do we need [`operator==()` and `serializeOp()`] here?
>
> not really. [...] a test here is the same as running a full simulator, and that is more the job for a regression test

Understood.  In that case I'll merge into master.

**Comment by bska** [comment]
jenkins build this please

**Pull request merged**
