### PR TITLE
using GenericFluidSystem for co2ptflash problem

### PR DESCRIPTION
**Pull request by GitPaean**

### CODE REVIEW

**Comment by bska** [comment]
Closing this briefly to enable the CI system to pick up the force-pushed changes.

**Comment by bska** [comment]
Reopening this to test the build again.

**Review by bska — APPROVED** [review]
Thanks a lot for the updates.  The build check is green and this looks good to me so I'll merge into master.

**Comment by lisajulia** [comment]
@GitPaean: The commit 454c12c69ab39c535d1cb3f8415f8ee80a21e5fc causes some problems for me, i.e.
```
/opm/models/io/baseoutputmodule.hh:426:68: error: request for member ‘data’ in ‘Opm::H2OAirFluidSystem<double, Opm::TabulatedComponent<double, Opm::H2O<double>, true> >::phaseName(i)’, which is of non-class type ‘const char*’
  426 |             snprintf(name, 512, pattern, FluidSystem::phaseName(i).data())
      |                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
```

Probably this commit is also involved: [0206bfa7dcf4a9360a37eb4bf2d73f903d289](https://github.com/OPM/opm-common/pull/3836/commits/0206bfa7dcf4a9360a37eb4bf2d73f903d2891de)

Can you maybe have a look? Thanks! :)

**Comment by blattms** [comment]
There is one occurrence where we still return const char*: [BaseFluidSystem.hpp#L77](https://github.com/GitPaean/opm-common/blob/27c8533513dbcbccf6cc87c6287055ef4ae845ff/opm/material/fluidsystems/BaseFluidSystem.hpp#L77).  Could that be problematic even though jenkins was fine?

**Comment by GitPaean** [comment]
> There is one occurrence where we still return const char*: [BaseFluidSystem.hpp#L77](https://github.com/GitPaean/opm-common/blob/27c8533513dbcbccf6cc87c6287055ef4ae845ff/opm/material/fluidsystems/BaseFluidSystem.hpp#L77). Could that be problematic even though jenkins was fine?

That function should not be called. not totally sure.

**Comment by GitPaean** [comment]
> @GitPaean: The commit [454c12c](https://github.com/OPM/opm-models/commit/454c12c69ab39c535d1cb3f8415f8ee80a21e5fc) causes some problems for me, i.e.
> 
> ```
> /opm/models/io/baseoutputmodule.hh:426:68: error: request for member ‘data’ in ‘Opm::H2OAirFluidSystem<double, Opm::TabulatedComponent<double, Opm::H2O<double>, true> >::phaseName(i)’, which is of non-class type ‘const char*’
>   426 |             snprintf(name, 512, pattern, FluidSystem::phaseName(i).data())
>       |                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
> ```
> 
> Probably this commit is also involved: [0206bfa7dcf4a9360a37eb4bf2d73f903d289](https://github.com/OPM/opm-common/pull/3836/commits/0206bfa7dcf4a9360a37eb4bf2d73f903d2891de)
> 
> Can you maybe have a look? Thanks! :)

Can you tell a little bit more how I can reproduce it?

**Comment by GitPaean** [comment]
It is likely caused by the `char*` in the Component. 

`opm-common/opm/material/components`.

**Comment by lisajulia** [comment]
@GitPaean: Thanks, yes, my opm-common was not updated properly - sorry!

**Pull request merged**
