### PR TITLE
Use temperature from depth in primaryvariable switching

### PR DESCRIPTION
**Pull request by totto82**
This bug could lead to oscillation between primary variables for non constant temperature cases.

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
The results looks qualitatively the same as expected. The bug introduced some oscillations in the model that seems to be improved with the fix. This also slightly change the time stepping. i.e we should make an update of data and get this fix in.   

image

**Review by atgeirr — APPROVED** [review]
This is good, should be merged.

**Comment by atgeirr** [comment]
jenkins build this update_data please

**Comment by totto82** [comment]
jenkins build this opm-tests=1051 please

**Comment by bska** [comment]
The new reference solutions have been installed on the CI system.  Merging this now to bring the overall system back to a consistent state.

**Pull request merged**
