### PR TITLE
bug fix: missing setRs added

### PR DESCRIPTION
**Pull request by plgbrts**
This fix solve a convergence issue when water disappears due to evaporation

### CODE REVIEW

**Comment by plgbrts** [comment]
jenkins build this please

**Comment by goncalvesmachadoc** [comment]
Can we add this to the Release 2022.10?

**Review by atgeirr — APPROVED** [review]
Looks good, can be merged when green. Added to release milestone.

**Comment by bska** [comment]
> Looks good, can be merged when green

Build is green.  I'll merge into master.  Thanks a lot for identifying and fixing this issue.

**Pull request merged**
