### PR TITLE
Faster assembly (rebased)

### PR DESCRIPTION
**Pull request by atgeirr**

### CODE REVIEW

**Comment by bska** [comment]
I take it this PR replaces #697?  If so, please close that one.

**Comment by atgeirr** [comment]
> I take it this PR replaces #697? If so, please close that one.

Probably, but there might be more coming in that branch that I will cherry-pick, so if it is ok I wait a little? The purpose of this PR for now is to enable testing.

**Comment by bska** [comment]
@atgeirr : Do you still want to merge this PR?

**Comment by atgeirr** [comment]
> @atgeirr : Do you still want to merge this PR?

No, closing. There is stuff here that may make it into future PRs.

**Pull request closed without merging**
