### PR TITLE
-- added missing include

### PR DESCRIPTION
**Pull request by hnil**
-- add definition of BCType

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Comment by akva2** [comment]
this needs to be conditional on HAVE_ECL_INPUT (i seriously dislike those defines, but...)

**Comment by atgeirr** [comment]
> this needs to be conditional on HAVE_ECL_INPUT (i seriously dislike those defines, but...)

I believe the whole BC treatment depends on this, so that means TpfaLinearizer also must be guarded by HAVE_ECL_INPUT?

**Comment by akva2** [comment]
yes, the whole thing. we deal with it separately.

**Pull request merged**
